# Generated by Django 3.2.13 on 2022-04-23 05:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrusel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25, verbose_name='nombre de la imagen')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Descripcion de imagen')),
                ('imagen', models.ImageField(upload_to='carruse/', verbose_name='Image')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('direccion', models.URLField(verbose_name='Direccion de categoria de productos')),
                ('fecha_registro', models.DateField(auto_now_add=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
