# Generated by Django 3.2.13 on 2022-04-25 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrusel', '0002_auto_20220424_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrusel',
            name='imagen_Carrusel',
            field=models.ImageField(upload_to='carrusel/', verbose_name='Image'),
        ),
    ]
