# Generated by Django 3.2.12 on 2022-04-21 04:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_marca', models.CharField(max_length=20, verbose_name='Nombre de la categoría')),
                ('descripcion_marca', models.CharField(blank=True, default='No', max_length=50, null=True, verbose_name='Descripción')),
                ('img_marca', models.ImageField(blank=True, default='img_defecto.jpg', null=True, upload_to='marcas_empresa/', verbose_name='Imagen')),
                ('fecha_registro', models.DateField(auto_now_add=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
