# Generated by Django 3.2.12 on 2022-04-21 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marca', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marca',
            name='nombre_marca',
            field=models.CharField(max_length=20, verbose_name='Nombre de la marca'),
        ),
    ]
